spring:
  application:
    name: LPS
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/lps?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8&zeroDateTimeBehavior=CONVERT_TO_NULL
    #url: jdbc:mysql://127.0.0.1:3306/lps?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: '000000'
  thymeleaf:
    cache: true

mybatis:
  mapper-locations: classpath:mapper/*.xml
server:
  servlet:
    context-path: /LPS
logging:
  file:
    name: webappLog/LPS.log